### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by jtmuller5** [AbdelbakiBoukerche/rsa_encrypt#11]
Love this package! It would be nice if there were a null safe version for Flutter 2.

**Comment by kannel-outis** [comment]
[https://github.com/kannel-outis/rsa_encrypt/tree/null-safety](https://github.com/kannel-outis/rsa_encrypt/tree/null-safety)

this could help...it's a folk and i'm currently using it in one of my projects

**Comment by nullptr-31** [comment]
Hi, thank you for using rsa_encrypt! Just wanted to let u know that **null safety is now supported in version 2.0.0**
Happy coding :)
