### ISSUE TITLE
What is the size of the key generated by this package?

### ISSUE THREAD

**Issue by DennisMuchiri** [AbdelbakiBoukerche/rsa_encrypt#18]
What is the size of the key generated by this package? e.g rsa-512, 1024 or 2048

@AbdelbakiBoukerche please help @AbdelbakiBoukerche

**Comment by Patrick762** [comment]
It seems like it's using 2048

In [line 260](https://github.com/AbdelbakiBoukerche/rsa_encrypt/blob/8933e2406e38e62e1d4d95dbcd2836a523ae1707/lib/rsa_encrypt.dart#L260) there's this part

```js
var rsapars = new RSAKeyGeneratorParameters(BigInt.from(65537), 2048, 5);
```

The second argument is the key size.

**Comment by DennisMuchiri** [comment]
Closing
