### ISSUE TITLE
Upgrade to pointycastle v2

### ISSUE THREAD

**Issue by eddiesTime** [AbdelbakiBoukerche/rsa_encrypt#5]
Hi, thanks for your effort.

Would you mind to upgrade the internal dependency to match the latest release? The [latest version](https://pub.dev/packages/pointycastle/changelog) contains some improvements and is now officially under new development.

**Comment by nullptr-31** [comment]
Working on it...

**Comment by nullptr-31** [comment]
rsa_encrypt 1.0.5 is now available, Thanks for your feedback.
