### ISSUE TITLE
no functions: encodePrivateKeyToPemPKCS1(keyPair.privateKey) & encodePublicKeyToPemPKCS1(keyPair.publicKey).

### ISSUE THREAD

**Issue by 312654929** [AbdelbakiBoukerche/rsa_encrypt#7]
When I use them, the prompt is undefined

**Comment by djackowski** [comment]
You have to use `RsaKeyHelper().encodePrivateKeyToPemPKCS1(keyPair.privateKey)` and `RsaKeyHelper().encodePublicKeyToPemPKCS1(keyPair.publicKey)`

**Comment by siman302** [comment]
How we convert the Public_Key_String on the other side, to RSAPublicKey.
There is no decode function which return the RSAPublicKey from the _publicKeyStr,

String _publicKeyStr = helper.encodePublicKeyToPemPKCS1(keys.publicKey);

**Comment by nullptr-31** [comment]
Hi, Thanks for showing interest in rsa_encrypt :)
As for your question, if you have a valid PEM String you can use the
parsePublicKeyFromPem (). This function takes the PEM String as a parameter
and returns a RSAPublicKey instance.
.
Happy Coding!
